# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlabuser',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='dlabuser',
            name='username',
            field=models.CharField(default='', max_length=10),
        ),
    ]
