# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 07:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20160823_1611'),
        ('members', '0002_auto_20160823_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', '남자'), ('W', '여자')], default='남자', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='dlabuser',
            name='gender',
            field=models.CharField(choices=[('M', '남자'), ('W', '여자')], default='남자', max_length=1),
        ),
        migrations.AddField(
            model_name='childuser',
            name='dlabuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='childuser',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.SemesterSubject'),
        ),
    ]
