# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20160823_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='childuser',
            name='age',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
