# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20160823_1611'),
        ('members', '0004_childuser_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('childName', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField(default=1)),
                ('gender', models.CharField(choices=[('M', '남자'), ('W', '여자')], default='남자', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ChildMemberSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.ChildMember')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.SemesterSubject')),
            ],
        ),
        migrations.RenameModel(
            old_name='DlabUser',
            new_name='Member',
        ),
        migrations.RemoveField(
            model_name='childuser',
            name='dlabuser',
        ),
        migrations.RemoveField(
            model_name='childuser',
            name='subject',
        ),
        migrations.DeleteModel(
            name='ChildUser',
        ),
        migrations.AddField(
            model_name='childmember',
            name='memberName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
    ]
