# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20160823_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childmember',
            name='memberName',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
