# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20160824_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(default='', max_length=10)),
                ('gender', models.CharField(choices=[('M', '남자'), ('W', '여자')], default='남자', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='childmember',
            name='memberName',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
    ]
