# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 07:05
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20160824_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childmember',
            name='age',
        ),
        migrations.RemoveField(
            model_name='member',
            name='gender',
        ),
        migrations.AddField(
            model_name='childmember',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='childmember',
            name='experience',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='childmember',
            name='school',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
