# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20160824_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='username',
            new_name='memberName',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
    ]
