# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20160825_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childmember',
            name='memberName',
        ),
        migrations.RemoveField(
            model_name='childmembersubject',
            name='childName',
        ),
        migrations.RemoveField(
            model_name='childmembersubject',
            name='subject',
        ),
        migrations.DeleteModel(
            name='ChildMember',
        ),
        migrations.DeleteModel(
            name='ChildMemberSubject',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
