# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 08:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_auto_20160826_1750'),
        ('members', '0011_auto_20160826_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childName', models.CharField(max_length=10)),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('gender', models.CharField(choices=[('M', '남자'), ('W', '여자')], default='남자', max_length=1)),
                ('school', models.CharField(default='', max_length=255)),
                ('experience', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildMemberSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.ChildMember')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.SemesterSubject')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('memberName', models.CharField(default='', max_length=10)),
                ('phoneNumber', models.CharField(blank=True, max_length=13)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('path', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='childmember',
            name='memberName',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
    ]
