# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SemesterClass',
            new_name='SemesterSubject',
        ),
    ]
