# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20160826_1749'),
        ('courses', '0002_auto_20160823_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='semestersubject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='semestersubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='module',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='SemesterSubject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
