# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20160816_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=128)),
                ('classCode', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='LevelModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.ClassLevel')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='moduleName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.LevelModule'),
        ),
    ]
