# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 07:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='DS-101', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('name', models.CharField(default='DS1', max_length=128, primary_key=True, serialize=False)),
                ('course', models.ForeignKey(default='Starter', on_delete=django.db.models.deletion.CASCADE, to='semi.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.ForeignKey(default='Sangyoon', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('name', models.CharField(default='2016-9', max_length=128, primary_key=True, serialize=False)),
                ('className', models.ManyToManyField(to='semi.Classes')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=128)),
                ('className', models.ForeignKey(default='DS-101', on_delete=django.db.models.deletion.CASCADE, to='semi.Classes')),
                ('semester', models.ForeignKey(default='2016-9', on_delete=django.db.models.deletion.CASCADE, to='semi.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semi.SemesterClass')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='moduleName',
            field=models.ForeignKey(default='DS1', on_delete=django.db.models.deletion.CASCADE, to='semi.Module'),
        ),
    ]
