# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterclass',
            name='classInfo',
            field=models.CharField(default='과목정보', max_length=128),
        ),
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
