# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi', '0002_auto_20160819_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterclass',
            name='classInfo',
        ),
    ]
