# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi', '0003_remove_semesterclass_classinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='id',
        ),
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
