# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi', '0004_auto_20160819_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterclass',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
