# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi', '0005_auto_20160819_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterclass',
            name='id',
        ),
        migrations.AlterField(
            model_name='semesterclass',
            name='time',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
