# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi', '0006_auto_20160819_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterclass',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='semesterclass',
            name='time',
            field=models.CharField(max_length=128),
        ),
    ]
