# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi', '0008_auto_20160819_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclass',
            name='course',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
