# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi', '0009_userclass_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclass',
            name='course',
        ),
    ]
