# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi', '0011_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='userName',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='userclass',
            old_name='userName',
            new_name='username',
        ),
    ]
