# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi', '0014_auto_20160820_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='username',
        ),
    ]
