# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassType',
            new_name='ClassLevel',
        ),
    ]
