# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20160816_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlevel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='levelmodule',
            name='id',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='id',
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='levelmodule',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
