# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20160817_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='levelName',
            field=models.ForeignKey(default='Starter', on_delete=django.db.models.deletion.CASCADE, to='timetable.ClassLevel'),
        ),
    ]
