# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_class_levelname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='levelName',
        ),
    ]
