# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_auto_20160818_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='moduleName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.ClassModule'),
        ),
    ]
